### ISSUE TITLE
Cannot build Veldrid example

### ISSUE THREAD

**Issue by JoshuaLamusga** [mellinoe/ImGui.NET#147]
I did a git clone of this repository today, then rebuilt the solution (which succeeded). I can run the XNA example without an error, but the Veldrid example fails to start, giving this error:

> SharpDX.SharpDXException: 'HRESULT: [0x887A002D], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.

With this stack trace:

>   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at Veldrid.D3D11.D3D11GraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 swapchainDesc)
   at Veldrid.GraphicsDevice.CreateD3D11(GraphicsDeviceOptions options, IntPtr hwnd, UInt32 width, UInt32 height)
   at Veldrid.StartupUtilities.VeldridStartup.CreateDefaultD3D11GraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, Sdl2Window& window, GraphicsDevice& gd)
   at ImGuiNET.Program.Main(String[] args) in C:\Users\Default.Josh\Desktop\imgui\ImGui.NET\src\ImGui.NET.SampleProgram\Program.cs:line 37

Built on Windows 8.0, 64-bit with Visual Studio 2019. Let me know if I need to check the dependencies for specific possible inconsistencies or provide any other information.

**Comment by tienery** [comment]
I know this issue is old, but thought I'd weigh in.

Is the DirectX 11 SDK installed? I don't think Windows 8 supplies that by default. Also try using `GraphicsBackend.OpenGL` in the third argument of the `CreateWindowAndGraphicsDevice` and see if that makes a difference in launching.
