### ISSUE TITLE
When trying to use the MonoGame example classes there is an error loading Microsoft.Xna.Framework.TextInputEventArgs

### ISSUE THREAD

**Issue by ChristianIvicevic** [mellinoe/ImGui.NET#170]
As noted in the title, when I copy the `DrawVertDeclaration.cs` and `ImGuiRenderer.cs` into my project with the  current NuGet package of ImGui.net the invocation of `SetupInput` in the constructor of the `ImGuiRenderer` class suddenly causes a cryptic exception:

```
System.TypeLoadException: Could not load type 'Microsoft.Xna.Framework.TextInputEventArgs' from assembly 'MonoPlayground, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.
  at at MonoPlayground.ImGuiRenderer.SetupInput()
  at Nightfall.ImGuiRenderer..ctor(Game game)
```

I am currently using MonoGame 3.8 and it feels as if this is the issue right now. Any ideas how to debug this or even fix this issue to be able to use ImGui in my MonoGame project?

**Comment by ChristianIvicevic** [comment]
I've already got an update - so I have been splitting the solution into two projects. The generic DesktopGL project based on .NET Core 3.1 and DesktopGL (duh.) and a .NETStandard 2.0 library that just contains the game code. The intention is that it's easier adding platform-specific code to the respective projects and have game code shared between all of them. This unfortunately causes issues though.

For reference I followed this WIP documentation: https://github.com/harry-cpp/MonoGame/blob/newprojdocs/Documentation/setting_up_project/setting_up_project_vscode.md

**Comment by ChristianIvicevic** [comment]
Quick update again, I noticed that the shared library was using version 3.7 of DesktopGL, after upgrading that to 3.8 as well it worked even with ImGui being in the shared library. It seems that the conflicting versions of DesktopGL were causing some issues.
