### ISSUE TITLE
igGetPlatformIO does not exist in cimgui

### ISSUE THREAD

**Issue by zeeshan595** [mellinoe/ImGui.NET#175]
When using `ImGui.GetPlatformIO()` it throws the following error on linux (Pop OS 20.04) dot net core 3.1

```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'igGetPlatformIO' in shared library 'cimgui'.
   at ImGuiNET.ImGuiNative.igGetPlatformIO()
   at ImGuiNET.ImGui.GetPlatformIO() in /home/zeeshan/Documents/Projects/ImGui.NET/src/ImGui.NET/Generated/ImGui.gen.cs:line 5898
   at ImGuiNET.ImGuiController..ctor(GraphicsDevice gd, Sdl2Window window, OutputDescription outputDescription, Int32 width, Int32 height) in /home/zeeshan/Documents/Projects/ImGui.NET/src/ImGui.NET.SampleProgram/ImGuiController.cs:line 86
   at ImGuiNET.Program.Main(String[] args) in /home/zeeshan/Documents/Projects/ImGui.NET/src/ImGui.NET.SampleProgram/Program.cs:line 49
```

**Comment by FrostplayGames** [comment]
Hi! I have the same problem as you. Did you manage to fix this in the end? If so, how?

**Comment by mellinoe** [comment]
Latest version of the docking branch here should be in a working state.
