### ISSUE TITLE
Exception has occurred: CLR/System.InvalidOperationException

### ISSUE THREAD

**Issue by FrostplayGames** [mellinoe/ImGui.NET#240]
Hi guys! I am having a problem with my code and unsure of the root cause to the issue. The error I keep getting is: **Exception has occurred: CLR/System.InvalidOperationException**

I have taken a look at the SampleProgram for writing the ImGuiController, and the error is occurring on Line 319 in ImGuiController.cs (the **foreach (MouseEvent mEvent in snapshot.MouseEvents)**).

**The full error:**
```
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Collection was modified; enumeration operation may not execute.'
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at FrostEngine.IMGUI.ImGuiController.UpdateImGuiInput(InputSnapshot snapshot) in C:\development\FrostEngine\FEngine\Engine\ImGui\ImGuiController.cs:line 319
   at FrostEngine.IMGUI.ImGuiController.Update(Single deltaSeconds, InputSnapshot snapshot) in C:\development\FrostEngine\FEngine\Engine\ImGui\ImGuiController.cs:line 291
   at Sandbox.Program.<>c.<Main>b__4_0() in C:\development\FrostEngine\Sandbox\Program.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Program.cs:**
```cs
using System;
using System.Threading;
using System.Linq;
using System.Numerics;
using Veldrid;
using ImGuiNET;
using FrostEngine;
using FrostEngine.IMGUI;

namespace Sandbox
{
    class Program
    {
        static Application m_Application;

        static CommandList m_CommandList;
        static ImGuiController m_ImGuiController;

        static Vector3 clearColor = new Vector3(0.45f, 0.55f, 0.6f);

        static void Main(string[] args)
        {
            m_Application = new Application(new WindowProps("Sandbox", 1280, 720));
            m_Application.Run();

            m_CommandList = m_Application.GetWindow().GetGraphicsDevice().ResourceFactory.CreateCommandList();
            m_ImGuiController = new ImGuiController(m_Application.GetWindow().GetGraphicsDevice(), m_Application.GetWindow().GetGraphicsDevice().MainSwapchain.Framebuffer.OutputDescription, m_Application.GetWindow().GetWidth(), m_Application.GetWindow().GetHeight());

            new Thread(() =>
            {
                while (m_Application.IsRunning())
                {
                    if (!m_Application.IsRunning()) break;

                    m_ImGuiController.Update(1f / 60f, m_Application.GetWindow().GetSnapshot());

                    RenderImGui();

                    m_CommandList.Begin();
                    m_CommandList.SetFramebuffer(m_Application.GetWindow().GetGraphicsDevice().MainSwapchain.Framebuffer);
                    m_CommandList.ClearColorTarget(0, new RgbaFloat(clearColor.X, clearColor.Y, clearColor.Z, 1f));
                    m_ImGuiController.Render(m_Application.GetWindow().GetGraphicsDevice(), m_CommandList);
                    m_CommandList.End();
                    m_Application.GetWindow().GetGraphicsDevice().SubmitCommands(m_CommandList);
                    m_Application.GetWindow().GetGraphicsDevice().SwapBuffers();
                }

                m_Application.GetWindow().GetGraphicsDevice().WaitForIdle();
                m_ImGuiController.Dispose();
                m_CommandList.Dispose();
                m_Application.GetWindow().GetGraphicsDevice().Dispose();
            }).Start();

            void RenderImGui()
            {
                ImGui.ShowDemoWindow();
            }

            new Game();
        }

        public class Game : Window
        {
            public override void OnWindowResize()
            {
                Debug.Log("Running OnWindowResize()", LogEnvironment.Client);

                GraphicsDevice m_GraphicsDevice = m_Application.GetWindow().GetGraphicsDevice();

                int windowWidth = m_Application.GetWindow().GetWidth();
                int windowHeight = m_Application.GetWindow().GetHeight();

                m_ImGuiController.WindowResize(windowWidth, windowHeight);

                base.OnWindowResize();
            }
        }
    }
}
```

**ImGuiController.cs:**
```cs
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Reflection;
using System.IO;
using System.Runtime.CompilerServices;
using Veldrid;
using ImGuiNET;

namespace FrostEngine.IMGUI
{
    public class ImGuiController : IDisposable
    {
        GraphicsDevice m_GraphicsDevice;
        bool frameBegun;

        // Veldrid objects
        DeviceBuffer m_VertexBuffer;
        DeviceBuffer m_IndexBuffer;
        DeviceBuffer m_ProjMatrixBuffer;
        Texture m_FontTexture;
        TextureView m_FontTextureView;
        Shader m_VertexShader;
        Shader m_FragmentShader;
        ResourceLayout m_Layout;
        ResourceLayout m_TextureLayout;
        Pipeline m_Pipeline;
        ResourceSet m_MainResourceSet;
        ResourceSet m_FontTextureResourceSet;

        IntPtr fontAtlasID = (IntPtr)1;
        bool controlDown;
        bool shiftDown;
        bool altDown;
        bool winKeyDown;

        int windowWidth;
        int windowHeight;
        Vector2 scaleFactor = Vector2.One;

        // Image trackers
        readonly Dictionary<TextureView, ResourceSetInfo> setsByView = new Dictionary<TextureView, ResourceSetInfo>();
        readonly Dictionary<Texture, TextureView> autoViewsByTexture = new Dictionary<Texture, TextureView>();
        readonly Dictionary<IntPtr, ResourceSetInfo> viewsByID = new Dictionary<IntPtr, ResourceSetInfo>();
        readonly List<IDisposable> ownedResources = new List<IDisposable>();
        
        int lastAssignedID = 100;

        public ImGuiController(GraphicsDevice graphicsDevice, OutputDescription outputDescription, int width, int height)
        {
            m_GraphicsDevice = graphicsDevice;
            windowWidth = width;
            windowHeight = height;

            IntPtr context = ImGui.CreateContext();
            ImGui.SetCurrentContext(context);
            var fonts = ImGui.GetIO().Fonts;
            fonts.AddFontDefault();

            CreateDeviceResources(graphicsDevice, outputDescription);
            SetKeyMappings();

            SetPerFrameImGuiData(1f / 60f);

            ImGui.NewFrame();
            frameBegun = true;
        }

        public void WindowResize(int width, int height)
        {
            windowWidth = width;
            windowHeight = height;
        }

        public void DestroyDeviceObjects()
        {
            Dispose();
        }

        public void CreateDeviceResources(GraphicsDevice graphicsDevice, OutputDescription outputDescription)
        {
            m_GraphicsDevice = graphicsDevice;

            ResourceFactory factory = graphicsDevice.ResourceFactory;

            m_VertexBuffer = factory.CreateBuffer(new BufferDescription(10000, BufferUsage.VertexBuffer | BufferUsage.Dynamic));
            m_VertexBuffer.Name = "FrostEngine.IMGUI Vertex Buffer";
            
            m_IndexBuffer = factory.CreateBuffer(new BufferDescription(2000, BufferUsage.IndexBuffer | BufferUsage.Dynamic));
            m_IndexBuffer.Name = "FrostEngine.IMGUI Index Buffer";

            RecreateFontDeviceTexture(graphicsDevice);

            m_ProjMatrixBuffer = factory.CreateBuffer(new BufferDescription(64, BufferUsage.UniformBuffer | BufferUsage.Dynamic));
            m_ProjMatrixBuffer.Name = "FrostEngine.IMGUI Projection Buffer";

            byte[] vertexShaderBytes = LoadEmbeddedShaderCode(graphicsDevice.ResourceFactory, "imgui-vertex", ShaderStages.Vertex);
            byte[] fragmentShaderBytes = LoadEmbeddedShaderCode(graphicsDevice.ResourceFactory, "imgui-frag", ShaderStages.Fragment);

            m_VertexShader = factory.CreateShader(new ShaderDescription(ShaderStages.Vertex, vertexShaderBytes, graphicsDevice.BackendType == GraphicsBackend.Metal ? "VS" : "main"));
            m_FragmentShader = factory.CreateShader(new ShaderDescription(ShaderStages.Fragment, fragmentShaderBytes, graphicsDevice.BackendType == GraphicsBackend.Metal ? "FS" : "main"));

            VertexLayoutDescription[] vertexLayouts = new VertexLayoutDescription[]
            {
                new VertexLayoutDescription(
                    new VertexElementDescription("in_position", VertexElementSemantic.Position, VertexElementFormat.Float2),
                    new VertexElementDescription("in_texCoord", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float2),
                    new VertexElementDescription("in_color", VertexElementSemantic.Color, VertexElementFormat.Byte4_Norm))
            };

            m_Layout = factory.CreateResourceLayout(new ResourceLayoutDescription(
                new ResourceLayoutElementDescription("ProjectionMatrixBuffer", ResourceKind.UniformBuffer, ShaderStages.Vertex),
                new ResourceLayoutElementDescription("MainSampler", ResourceKind.Sampler, ShaderStages.Fragment)
            ));

            m_TextureLayout = factory.CreateResourceLayout(new ResourceLayoutDescription(
                new ResourceLayoutElementDescription("MainTexture", ResourceKind.TextureReadOnly, ShaderStages.Fragment)
            ));

            GraphicsPipelineDescription pipelineDescription = new GraphicsPipelineDescription(
                BlendStateDescription.SingleAlphaBlend,
                new DepthStencilStateDescription(false, false, ComparisonKind.Always),
                new RasterizerStateDescription(FaceCullMode.None, PolygonFillMode.Solid, FrontFace.Clockwise, false, true),
                PrimitiveTopology.TriangleList,
                new ShaderSetDescription(vertexLayouts, new[] { m_VertexShader, m_FragmentShader }),
                new ResourceLayout[] { m_Layout, m_TextureLayout },
                outputDescription,
                ResourceBindingModel.Default
            );

            m_Pipeline = factory.CreateGraphicsPipeline(ref pipelineDescription);

            m_MainResourceSet = factory.CreateResourceSet(new ResourceSetDescription(m_Layout, m_ProjMatrixBuffer, graphicsDevice.PointSampler));

            m_FontTextureResourceSet = factory.CreateResourceSet(new ResourceSetDescription(m_TextureLayout, m_FontTextureView));
        }

        public IntPtr GetOrCreateImGuiBinding(ResourceFactory factory, TextureView textureView)
        {
            if (!setsByView.TryGetValue(textureView, out ResourceSetInfo resSetInfo))
            {
                ResourceSet resSet = factory.CreateResourceSet(new ResourceSetDescription(m_TextureLayout, textureView));
                resSetInfo = new ResourceSetInfo(GetNextImGuiBindingID(), resSet);

                setsByView.Add(textureView, resSetInfo);
                viewsByID.Add(resSetInfo.ImGuiBinding, resSetInfo);
                ownedResources.Add(resSet);
            }

            return resSetInfo.ImGuiBinding;
        }

        IntPtr GetNextImGuiBindingID()
        {
            int newID = lastAssignedID++;
            return (IntPtr)newID;
        }

        public IntPtr GetOrCreateImGuiBinding(ResourceFactory factory, Texture texture)
        {
            if (!autoViewsByTexture.TryGetValue(texture, out TextureView textureView))
            {
                textureView = factory.CreateTextureView(texture);
                autoViewsByTexture.Add(texture, textureView);
                ownedResources.Add(textureView);
            }

            return GetOrCreateImGuiBinding(factory, textureView);
        }

        public ResourceSet GetImageResourceSet(IntPtr imGuiBinding)
        {
            if (!viewsByID.TryGetValue(imGuiBinding, out ResourceSetInfo resSetInfo))
            {
                throw new InvalidOperationException("No registered ImGui binding with ID " + imGuiBinding.ToString());
            }

            return resSetInfo.ResourceSet;
        }

        public void ClearCachedImageResources()
        {
            foreach (IDisposable resource in ownedResources)
            {
                resource.Dispose();
            }

            ownedResources.Clear();
            setsByView.Clear();
            viewsByID.Clear();
            autoViewsByTexture.Clear();
            lastAssignedID = 100;
        }

        byte[] LoadEmbeddedShaderCode(ResourceFactory factory, string name, ShaderStages stage)
        {
            switch (factory.BackendType)
            {
                case GraphicsBackend.Direct3D11:
                {
                    string resourceName = name + ".hlsl.bytes";
                    return GetEmbeddedResourceBytes(resourceName);
                }
                case GraphicsBackend.OpenGL:
                {
                    string resourceName = name + ".glsl";
                    return GetEmbeddedResourceBytes(resourceName);
                }
                case GraphicsBackend.Vulkan:
                {
                    string resourceName = name + ".spv";
                    return GetEmbeddedResourceBytes(resourceName);
                }
                case GraphicsBackend.Metal:
                {
                    string resourceName = name + ".metallib";
                    return GetEmbeddedResourceBytes(resourceName);
                }
                default:
                    throw new NotImplementedException();
            }
        }

        byte[] GetEmbeddedResourceBytes(string resourceName)
        {
            Assembly assembly = typeof(ImGuiController).Assembly;
            using (Stream stream = assembly.GetManifestResourceStream(resourceName))
            {
                byte[] ret = new byte[stream.Length];
                stream.Read(ret, 0, (int)stream.Length);
                return ret;
            }
        }

        public void RecreateFontDeviceTexture(GraphicsDevice graphicsDevice)
        {
            ImGuiIOPtr io = ImGui.GetIO();

            IntPtr pixels;
            int width, height, bytesPerPixel;

            io.Fonts.GetTexDataAsRGBA32(out pixels, out width, out height, out bytesPerPixel);
            io.Fonts.SetTexID(fontAtlasID);

            m_FontTexture = graphicsDevice.ResourceFactory.CreateTexture(TextureDescription.Texture2D(
                (uint)width,
                (uint)height,
                1,
                1,
                PixelFormat.R8_G8_B8_A8_UNorm,
                TextureUsage.Sampled
            ));

            m_FontTexture.Name = "FrostEngine.IMGUI Font Texture";

            graphicsDevice.UpdateTexture(
                m_FontTexture,
                pixels,
                (uint)(bytesPerPixel * width * height),
                0,
                0,
                0,
                (uint)width,
                (uint)height,
                1,
                0,
                0
            );

            m_FontTextureView = graphicsDevice.ResourceFactory.CreateTextureView(m_FontTexture);

            io.Fonts.ClearTexData();
        }

        public void Render(GraphicsDevice graphicsDevice, CommandList cmdList)
        {
            if (frameBegun)
            {
                frameBegun = false;
                ImGui.Render();
                RenderImDrawData(ImGui.GetDrawData(), graphicsDevice, cmdList);
            }
        }

        public void Update(float deltaSeconds, InputSnapshot snapshot)
        {
            if (frameBegun)
                ImGui.Render();

            SetPerFrameImGuiData(deltaSeconds);
            UpdateImGuiInput(snapshot);

            frameBegun = true;
            ImGui.NewFrame();
        }

        void SetPerFrameImGuiData(float deltaSeconds)
        {
            ImGuiIOPtr io = ImGui.GetIO();
            io.DisplaySize = new Vector2(
                windowWidth / scaleFactor.X,
                windowHeight / scaleFactor.Y
            );

            io.DisplayFramebufferScale = scaleFactor;
            io.DeltaTime = deltaSeconds;
        }

        void UpdateImGuiInput(InputSnapshot snapshot)
        {
            ImGuiIOPtr io = ImGui.GetIO();

            Vector2 mousePos = snapshot.MousePosition;

            bool leftPressed = false;
            bool middlePressed = false;
            bool rightPressed = false;

            foreach (MouseEvent mEvent in snapshot.MouseEvents)
            {
                if (mEvent.Down)
                {
                    switch (mEvent.MouseButton)
                    {
                        case MouseButton.Left:
                            leftPressed = true;
                            break;
                        case MouseButton.Middle:
                            middlePressed = true;
                            break;
                        case MouseButton.Right:
                            rightPressed = true;
                            break;
                    }
                }
            }

            io.MouseDown[0] = leftPressed || snapshot.IsMouseDown(MouseButton.Left);
            io.MouseDown[1] = rightPressed || snapshot.IsMouseDown(MouseButton.Right);
            io.MouseDown[2] = middlePressed || snapshot.IsMouseDown(MouseButton.Middle);

            io.MousePos = mousePos;
            io.MouseWheel = snapshot.WheelDelta;

            IReadOnlyList<char> keyCharPresses = snapshot.KeyCharPresses;
            for (int i = 0; i < keyCharPresses.Count; i++)
            {
                char c = keyCharPresses[i];
                io.AddInputCharacter(c);
            }

            IReadOnlyList<KeyEvent> keyEvents = snapshot.KeyEvents;
            for (int i = 1; i < keyEvents.Count; i++)
            {
                KeyEvent keyEvent = keyEvents[i];
                io.KeysDown[(int)keyEvent.Key] = keyEvent.Down;

                if (keyEvent.Key == Key.ControlLeft)
                {
                    controlDown = keyEvent.Down;
                }
                if (keyEvent.Key == Key.ShiftLeft)
                {
                    shiftDown = keyEvent.Down;
                }
                if (keyEvent.Key == Key.AltLeft)
                {
                    altDown = keyEvent.Down;
                }
                if (keyEvent.Key == Key.WinLeft)
                {
                    winKeyDown = keyEvent.Down;
                }
            }

            io.KeyCtrl = controlDown;
            io.KeyAlt = altDown;
            io.KeyShift = shiftDown;
            io.KeySuper = winKeyDown;
        }

        private static void SetKeyMappings()
        {
            ImGuiIOPtr io = ImGui.GetIO();

            io.KeyMap[(int)ImGuiKey.Tab] = (int)Key.Tab;
            io.KeyMap[(int)ImGuiKey.LeftArrow] = (int)Key.Left;
            io.KeyMap[(int)ImGuiKey.RightArrow] = (int)Key.Right;
            io.KeyMap[(int)ImGuiKey.UpArrow] = (int)Key.Up;
            io.KeyMap[(int)ImGuiKey.DownArrow] = (int)Key.Down;
            io.KeyMap[(int)ImGuiKey.PageUp] = (int)Key.PageUp;
            io.KeyMap[(int)ImGuiKey.PageDown] = (int)Key.PageDown;
            io.KeyMap[(int)ImGuiKey.Home] = (int)Key.Home;
            io.KeyMap[(int)ImGuiKey.End] = (int)Key.End;
            io.KeyMap[(int)ImGuiKey.Delete] = (int)Key.Delete;
            io.KeyMap[(int)ImGuiKey.Backspace] = (int)Key.BackSpace;
            io.KeyMap[(int)ImGuiKey.Enter] = (int)Key.Enter;
            io.KeyMap[(int)ImGuiKey.Escape] = (int)Key.Escape;
            io.KeyMap[(int)ImGuiKey.Space] = (int)Key.Space;
            io.KeyMap[(int)ImGuiKey.A] = (int)Key.A;
            io.KeyMap[(int)ImGuiKey.C] = (int)Key.C;
            io.KeyMap[(int)ImGuiKey.V] = (int)Key.V;
            io.KeyMap[(int)ImGuiKey.X] = (int)Key.X;
            io.KeyMap[(int)ImGuiKey.Y] = (int)Key.Y;
            io.KeyMap[(int)ImGuiKey.Z] = (int)Key.Z;
        }

        void RenderImDrawData(ImDrawDataPtr drawDataPtr, GraphicsDevice graphicsDevice, CommandList cmdList)
        {
            uint vertexOffsetInVertices = 0;
            uint indexOffsetInElements = 0;

            if (drawDataPtr.CmdListsCount == 0)
            {
                return;
            }

            uint totalVBSize = (uint)(drawDataPtr.TotalVtxCount * Unsafe.SizeOf<ImDrawVert>());
            if (totalVBSize > m_VertexBuffer.SizeInBytes)
            {
                graphicsDevice.DisposeWhenIdle(m_VertexBuffer);
                m_VertexBuffer = graphicsDevice.ResourceFactory.CreateBuffer(new BufferDescription((uint)(totalVBSize * 1.5f), BufferUsage.VertexBuffer | BufferUsage.Dynamic));
            }

            uint totalIBSize = (uint)(drawDataPtr.TotalIdxCount * sizeof(ushort));
            if (totalIBSize > m_IndexBuffer.SizeInBytes)
            {
                graphicsDevice.DisposeWhenIdle(m_IndexBuffer);
                m_IndexBuffer = graphicsDevice.ResourceFactory.CreateBuffer(new BufferDescription((uint)(totalIBSize * 1.5f), BufferUsage.IndexBuffer | BufferUsage.Dynamic));
            }

            for (int i = 0; i < drawDataPtr.CmdListsCount; i++)
            {
                ImDrawListPtr cList = drawDataPtr.CmdListsRange[i];

                cmdList.UpdateBuffer(
                    m_VertexBuffer,
                    vertexOffsetInVertices * (uint)Unsafe.SizeOf<ImDrawVert>(),
                    cList.VtxBuffer.Data,
                    (uint)(cList.VtxBuffer.Size * Unsafe.SizeOf<ImDrawVert>())
                );

                cmdList.UpdateBuffer(
                    m_IndexBuffer,
                    indexOffsetInElements * sizeof(ushort),
                    cList.IdxBuffer.Data,
                    (uint)(cList.IdxBuffer.Size * sizeof(ushort))
                );

                vertexOffsetInVertices += (uint)cList.VtxBuffer.Size;
                indexOffsetInElements += (uint)cList.IdxBuffer.Size;
            }

            ImGuiIOPtr io = ImGui.GetIO();
            Matrix4x4 mvp = Matrix4x4.CreateOrthographicOffCenter(
                0f,
                io.DisplaySize.X,
                io.DisplaySize.Y,
                0.0f,
                -1.0f,
                1.0f
            );

            graphicsDevice.UpdateBuffer(m_ProjMatrixBuffer, 0, ref mvp);

            cmdList.SetVertexBuffer(0, m_VertexBuffer);
            cmdList.SetIndexBuffer(m_IndexBuffer, IndexFormat.UInt16);
            cmdList.SetPipeline(m_Pipeline);
            cmdList.SetGraphicsResourceSet(0, m_MainResourceSet);

            drawDataPtr.ScaleClipRects(io.DisplayFramebufferScale);

            int vtxOffset = 0;
            int idxOffset = 0;
            for (int n = 0; n < drawDataPtr.CmdListsCount; n++)
            {
                ImDrawListPtr cList = drawDataPtr.CmdListsRange[n];
                for (int cmdI = 0; cmdI < cList.CmdBuffer.Size; cmdI++)
                {
                    ImDrawCmdPtr pCmd = cList.CmdBuffer[cmdI];
                    if (pCmd.UserCallback != IntPtr.Zero)
                    {
                        throw new NotImplementedException();
                    }
                    else
                    {
                        if (pCmd.TextureId != IntPtr.Zero)
                        {
                            if (pCmd.TextureId == fontAtlasID)
                            {
                                cmdList.SetGraphicsResourceSet(1, m_FontTextureResourceSet);
                            }
                            else
                            {
                                cmdList.SetGraphicsResourceSet(1, GetImageResourceSet(pCmd.TextureId));
                            }
                        }

                        cmdList.SetScissorRect(
                            0,
                            (uint)pCmd.ClipRect.X,
                            (uint)pCmd.ClipRect.Y,
                            (uint)(pCmd.ClipRect.Z - pCmd.ClipRect.X),
                            (uint)(pCmd.ClipRect.W - pCmd.ClipRect.Y)
                        );

                        cmdList.DrawIndexed(pCmd.ElemCount, 1, (uint)idxOffset, vtxOffset, 0);
                    }

                    idxOffset += (int)pCmd.ElemCount;
                }

                vtxOffset += cList.VtxBuffer.Size;
            }
        }

        public void Dispose()
        {
            m_VertexBuffer.Dispose();
            m_IndexBuffer.Dispose();
            m_ProjMatrixBuffer.Dispose();
            m_FontTexture.Dispose();
            m_FontTextureView.Dispose();
            m_VertexShader.Dispose();
            m_FragmentShader.Dispose();
            m_Layout.Dispose();
            m_TextureLayout.Dispose();
            m_Pipeline.Dispose();
            m_MainResourceSet.Dispose();

            foreach (IDisposable resource in ownedResources)
            {
                resource.Dispose();
            }
        }

        struct ResourceSetInfo
        {
            public readonly IntPtr ImGuiBinding;
            public readonly ResourceSet ResourceSet;

            public ResourceSetInfo(IntPtr imGuiBinding, ResourceSet resourceSet)
            {
                ImGuiBinding = imGuiBinding;
                ResourceSet = resourceSet;
            }
        }
    }
}
```

**Window.cs:**
```cs
using System;
using System.Threading;
using Veldrid;
using Veldrid.Sdl2;
using Veldrid.StartupUtilities;

namespace FrostEngine
{
    public class WindowProps
    {
        public string Title;
        public int Width;
        public int Height;

        public WindowProps(string windowTitle = "Frost App", int windowWidth = 1280, int windowHeight = 720)
        {
            Title = windowTitle;
            Width = windowWidth;
            Height = windowHeight;
        }
    };

    // TODO: Call GraphicsDevice.SwapBuffers() somewhere
    // TODO: Call GraphicsDevice.WaitForIdle(), GraphicsDevice.Dispose() somewhere
    public class Window
    {
        Sdl2Window window;
        static GraphicsDevice m_GraphicsDevice;

        InputSnapshot snapshot;

        public Window() {}

        public Window(WindowProps props)
        {
            Debug.Info($"Creating window: {props.Title} ({props.Width}, {props.Height})", LogEnvironment.Engine);

            WindowCreateInfo m_WindowCreateInfo = new WindowCreateInfo();
            
            m_WindowCreateInfo.X = 100;
            m_WindowCreateInfo.Y = 100;
            m_WindowCreateInfo.WindowWidth = props.Width;
            m_WindowCreateInfo.WindowHeight = props.Height;
            m_WindowCreateInfo.WindowTitle = props.Title;

            window = VeldridStartup.CreateWindow(ref m_WindowCreateInfo);

            GraphicsDeviceOptions m_GraphicsDeviceOptions = new GraphicsDeviceOptions();
            m_GraphicsDeviceOptions.PreferStandardClipSpaceYDirection = true;
            m_GraphicsDeviceOptions.PreferDepthRangeZeroToOne = true;

            m_GraphicsDevice = VeldridStartup.CreateGraphicsDevice(window, m_GraphicsDeviceOptions);

            if (window == null)
                Debug.Error($"Failed to create {props.Title}", LogEnvironment.Engine);

            window.Resized += () => OnWindowResize();

            window.Closing += () => Environment.Exit(0);
            window.Closed += () => Environment.Exit(0);
        }

        public void KeepAlive()
        {
            new Thread(() =>
            {
                while (window.Exists)
                {
                    snapshot = window.PumpEvents();
                }
            }).Start();
        }

        public void Close()
        {
            if (window.Exists)
                window.Close();
        }

        public void SetVisible(bool visible) { window.Visible = visible; }
        public bool GetVisible() { return window.Visible; }

        public void SetBorderVisible(bool visible) { window.BorderVisible = visible; }
        public bool GetBorderVisible() { return window.BorderVisible; }

        public int GetWidth() { return window.Width; }
        public int GetHeight() { return window.Height; }

        public InputSnapshot GetSnapshot() { return snapshot; }

        public GraphicsDevice GetGraphicsDevice() { return m_GraphicsDevice; }

        public virtual void OnWindowResize() {}
    }
}
```

**Application.cs:**
```cs
using System;

namespace FrostEngine
{
    public class Application
    {
        Window m_Window;

        bool m_Running = false;

        public Application(WindowProps props)
        {
            m_Window = new Window(new WindowProps(props.Title, props.Width, props.Height));
        }

        public void Run()
        {
            m_Window.KeepAlive();
            m_Running = true;
        }

        public bool IsRunning() { return m_Running; }

        public Window GetWindow() { return m_Window; }
    }
}
```

**Comment by mellinoe** [comment]
Based on some of the first sections in that code, it seems like you have a multi-threaded setup going on. The exception in question is complaining that the input snapshot was modified while you were running a `foreach` on it. Accessing that data isn't thread-safe, so if you want to have a second threat continuously pumping the window's message loop and producing new input snapshots, you'll have to use some kind of synchronization mechanism here.

**Comment by FrostplayGames** [comment]
> Based on some of the first sections in that code, it seems like you have a multi-threaded setup going on. The exception in question is complaining that the input snapshot was modified while you were running a `foreach` on it. Accessing that data isn't thread-safe, so if you want to have a second threat continuously pumping the window's message loop and producing new input snapshots, you'll have to use some kind of synchronization mechanism here.

Thanks for the response, I actually managed to figure this out already but thank you! I took the while loop out of a new thread which fixed my problem.

**Comment by FrostplayGames** [comment]
> Based on some of the first sections in that code, it seems like you have a multi-threaded setup going on. The exception in question is complaining that the input snapshot was modified while you were running a `foreach` on it. Accessing that data isn't thread-safe, so if you want to have a second threat continuously pumping the window's message loop and producing new input snapshots, you'll have to use some kind of synchronization mechanism here.

Can I please just quickly raise another issue I am having with ImGuiController.cs from the docking branch? When I run my application, I get an error: `System.EntryPointNotFoundException: Unable to find an entry point named 'igGetPlatformIO' in DLL 'cimgui'` - I currently have ImGuiNET.Docking from NuGet packages.

**Comment by mellinoe** [comment]
> I currently have ImGuiNET.Docking from NuGet packages

I'm not really sure what that means. The regular NuGet package is built from the docking branch these days, though. The docking branch here is now fully up-to-date with the master branch, and has updated cimgui binaries. If you're trying to mix-and-match versions of the NuGet packages with the code in the GitHub repo you will might hit some compatibility issues, so it's probably best to stick to a version of the ImGuiController that matches the release you are using (or just use something like Veldrid.ImGui which also has regular stable NuGet releases).

**Comment by FrostplayGames** [comment]
> > I currently have ImGuiNET.Docking from NuGet packages
> 
> I'm not really sure what that means. The regular NuGet package is built from the docking branch these days, though. The docking branch here is now fully up-to-date with the master branch, and has updated cimgui binaries. If you're trying to mix-and-match versions of the NuGet packages with the code in the GitHub repo you will might hit some compatibility issues, so it's probably best to stick to a version of the ImGuiController that matches the release you are using (or just use something like Veldrid.ImGui which also has regular stable NuGet releases).

Okay, thank you! I will stick to using only the things on the latest version.
