### ISSUE TITLE
Sample Projects broken since ImGuizmo, imnodes, ImPlot merge to master

### ISSUE THREAD

**Issue by sqrMin1** [mellinoe/ImGui.NET#241]
Both the Veldrid and the XNA sample project are not working anymore since the above mentioned update to the master branch #218 

They are both crashing at the same line in **ImGuiRenderer**:
https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram.XNA/ImGuiRenderer.cs#L336

With a **System.AccessViolationException** and the following StackTrace:

```
at System.Runtime.CompilerServices.Unsafe.Read[T](Void* source)
   at ImGuiNET.RangePtrAccessor`1.get_Item(Int32 index) in C:\Users\mhaer\Source\Repos\ImGui.NET2\src\ImGui.NET\RangeAccessor.cs:line 56
   at ImGuiNET.SampleProgram.XNA.ImGuiRenderer.UpdateBuffers(ImDrawDataPtr drawData) in C:\Users\mhaer\Source\Repos\ImGui.NET2\src\ImGui.NET.SampleProgram.XNA\ImGuiRenderer.cs:line 308
   at ImGuiNET.SampleProgram.XNA.ImGuiRenderer.RenderDrawData(ImDrawDataPtr drawData) in C:\Users\mhaer\Source\Repos\ImGui.NET2\src\ImGui.NET.SampleProgram.XNA\ImGuiRenderer.cs:line 267
   at ImGuiNET.SampleProgram.XNA.ImGuiRenderer.AfterLayout() in C:\Users\mhaer\Source\Repos\ImGui.NET2\src\ImGui.NET.SampleProgram.XNA\ImGuiRenderer.cs:line 134
   at ImGuiNET.SampleProgram.XNA.SampleGame.Draw(GameTime gameTime) in C:\Users\mhaer\Source\Repos\ImGui.NET2\src\ImGui.NET.SampleProgram.XNA\SampleGame.cs:line 66
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at ImGuiNET.SampleProgram.XNA.Program.Main(String[] args) in C:\Users\mhaer\Source\Repos\ImGui.NET2\src\ImGui.NET.SampleProgram.XNA\Program.cs:line 7
```

It is also pointing to this line in the **RangeAccessor**:
https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/RangeAccessor.cs#L56

Is there anything I need to setup with the new update before the sample projects will work again?

I tested with the current, unmodified master branch.

**Comment by mellinoe** [comment]
The native binaries were out of sync there, but everything should be fixed if you sync again.
