### ISSUE TITLE
ImGui.GetClipboardText fails

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/ImGui.NET#256]
ImGui.GetClipboardText fails and there doesn't seem to be any use of it on the official c++ demo file
```
/snap/rider/201/lib/ReSharperHost/linux-x64/dotnet/dotnet exec /snap/rider/201/lib/ReSharperHost/JetBrains.Debugger.Worker.exe --mode=client --frontend-port=35309 --plugins=/snap/rider/201/plugins/rider-unity/dotnetDebuggerWorker
INFO: Initializing raylib 3.5
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1680 x 1050
INFO:     > Render size:  800 x 600
INFO:     > Screen size:  800 x 600
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce GTX 650/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 460.73.01
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 350
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 3] Texture created successfully (512x64 - 1 mipmaps)
System.NullReferenceException: Object reference not set to an instance of an object.
   at ImGuiNET.Util.StringFromPtr(Byte* ptr)
   at ImGuiNET.ImGui.GetClipboardText()
   at GameSharp.GuiModule.InputStr(String name, String& value) in /home/shadowblitz16/RiderProjects/GameSharp/GameSharp/Core/Modules/GuiModule.cs:line 326
   at GameSharp.GuiModule.InspectorContents(Object self) in /home/shadowblitz16/RiderProjects/GameSharp/GameSharp/Core/Modules/GuiModule.cs:line 155
   at GameSharp.GuiModule.Inspector(Object self) in /home/shadowblitz16/RiderProjects/GameSharp/GameSharp/Core/Modules/GuiModule.cs:line 24
   at GameSharp.Entity.OnInspect() in /home/shadowblitz16/RiderProjects/GameSharp/GameSharp/Core/Assets/ObjModule/Entity.cs:line 35
   at GameSharp.Scene`1.Inspect() in /home/shadowblitz16/RiderProjects/GameSharp/GameSharp/Core/Assets/ObjModule/Scene.cs:line 27
   at GameSharpTests.Program.OnGui() in /home/shadowblitz16/RiderProjects/GameSharp/GameSharpTests/Program.cs:line 18
   at GameSharp.Window.Run() in /home/shadowblitz16/RiderProjects/GameSharp/GameSharp/Core/Defines/Window.cs:line 115

```cs
        public bool InputStr(string name, ref string value)
        {
            byte[] buffer = null;
            int    clipboard = ImGui.GetClipboardText() == null ? 0 : ImGui.GetClipboardText().Length;
            //Never reaches fails at this point ^
```

**Comment by Shadowblitz16** [comment]
here is my repo. look in GuiModule.InputStr
https://github.com/Shadowblitz16/GameSharp/blob/master/GameSharp/Core/Modules/GuiModule.cs
